--- #YAML:1.0
name:               Apache2-AuthTicketLDAP
version:            0.02
abstract:           Cookie Ticketing with LDAP Authentication
author:
    - Stephen Olander-Waters <stephenw@stedwards.edu>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Apache::AuthTicket:  0.93
    Cache::FastMmap:     1.40
    CHI:                 0.55
    Digest::SHA:         0
    Net::LDAP:           0.46
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
