---
abstract: 'Cookie Ticketing with LDAP Authentication'
author:
  - 'Stephen Olander-Waters <stephenw@stedwards.edu>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Apache2-AuthTicketLDAP
no_index:
  directory:
    - t
    - inc
requires:
  Apache::AuthTicket: 0.93
  CHI: 0.55
  Cache::FastMmap: 1.40
  Digest::SHA: 0
  Net::LDAP: 0.46
version: 0.01
